Create a console based usage for ruby
alexiscyber14/SCHOOL_LIB pull request #4
Opened 2023-05-23 08:12 UTC by alexiscyber14

Requirements:
Create a app.rb file that will serve as your console app entry-point. It should have methods that do the following:
List all books.
List all people.
Create a person (teacher or student, not a plain Person).
Create a book.
Create a rental.
List all rentals for a given person id.
In your main.rb define the entry point, this will be a method called main that is invoked at the end of your file. This method should do the following:
Present the user with a list of options to perform.
Lets users choose an option.
If needed, ask for parameters for the option.
Have a way to quit the app.

2023-05-23 10:06 UTC, Ibizugbe reviewed
Hi @alexiscyber14 👋👋👋, 

![INVALID](https://github.com/alexiscyber14/SCHOOL_LIB/assets/64643995/077bb4d8-aa39-4ad5-9028-9499bacfa6fe)


While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that doesn't have all section of the readme properly filled🥲. Kindly add the contributions, show your support, usage and acknowledgement sections and fill them with the appropriate content for this project👍.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2023-05-23 10:21 UTC, TedLivist reviewed
## STATUS: INVALID CODE REVIEW REQUEST 🛑 🛑

Hi @alexiscyber14,

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

### You have not added all the sections required by the previous reviewer. Your table of contents has links for Usage, Contributing, etc. But they are not leading anywhere. For a professional README, we should not have broken links. Kindly add the sections to the README and ensure they all work correctly.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear. And please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2023-05-23 20:22 UTC, danmainah requested changes
Hi @alexiscyber14 , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
✔️ Linter setup correctly and all checks are passing
✔️  Good design of the app, easier to follow commands.

# Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- x
- y
- z

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2023-05-23 20:22 UTC, danmainah commented on main.rb
> +end
- [ ] @alexiscyber14 great work implementing the changes requested, however, I would suggest when listing created people while creating the rentals, it would be nice listing their id as in the video example that way it is easier to reference  the id when checking rentals for an individual immediately after creating the rental to confirm its created:


Given Design          |  Your design     
:-------------------------:|:-------------------------:
![image](https://github.com/alexiscyber14/SCHOOL_LIB/assets/61408860/9b8ffc21-a671-41de-b1fc-9f8c18ac8722)  | ![image](https://github.com/alexiscyber14/SCHOOL_LIB/assets/61408860/825eda3b-3c17-4a27-9ea5-36259407f0bf)

2023-05-23 20:22 UTC, danmainah commented on main.rb
> +end
- [ ] [optional] @alexiscyber14 it would be nice if you added the `Welcome to School Library App!` when a person opens the app.

2023-05-23 23:06 UTC, Omar-Muhamad reviewed
# Invalid ❌

Hi @alexiscyber14,

#### While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

#### Your Code Review Request is marked as invalid for this reason:

- [ ] Some linters checks are not passed. Please make sure that all checks are passing and green.


Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **Does not count** into the code reviews limit._

2023-05-23 23:22 UTC, addod19 requested changes
### Hi @alexiscyber14, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


 ## Highlights
- [ ] Great job addressing some of the comments :rocket: awesome


 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-23 23:22 UTC, addod19 commented on app.rb
> +    if book_choice? || book_choice > @books.length
- [ ] It would be better if our app will allow us to create a rental is seen in the requirement video, here is the outcome of our app when testing it
![Screenshot from 2023-05-23 23-10-17](https://github.com/alexiscyber14/SCHOOL_LIB/assets/46388113/3e4450b3-d0ca-4887-96dc-0bb770d89192)

2023-05-23 23:22 UTC, addod19 commented on app.rb
> +    end
- [ ] In the requirement video, even when creating a student and we select parent permission as `N`, we should be able to create a student, however, our app prevents us from creating a student. Let us kindly fix it
Here is our app screenshot
![Screenshot from 2023-05-23 23-15-23](https://github.com/alexiscyber14/SCHOOL_LIB/assets/46388113/ef461370-c71b-4ad1-9254-66ce2363d89e)

Here is the requirement
![Screenshot from 2023-05-23 23-08-53](https://github.com/alexiscyber14/SCHOOL_LIB/assets/46388113/a1fd1e28-3660-420e-947a-130261c21bd1)

2023-05-24 06:42 UTC, arslanbisharat commented
Hi @alexiscyber14,
Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights

- The Pull Request has a proper title and description. ✔️ 
- You have added a descriptive Readme file. Good Job. ✔️ 
- There is no linter error is present. ✔️ 
- Project has met all the technical aspects you needed for this project. Keep rocking! ✔️ 


## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-24 06:55 UTC, merged